#!/usr/bin/env node
/**
 * Generate `usage.kdl` from the commander tree.
 *
 * The [`usage`](https://usage.jdx.dev) Rust binary consumes the KDL spec to
 * produce shell completions (bash/zsh/fish/PowerShell/nu) and manpages.
 *
 * Run:
 *   pnpm run gen-usage           — regenerate and write usage.kdl
 *   pnpm run gen-usage --check   — fail if the committed file is out of date
 *
 * `pnpm verify` chains the `--check` mode so CI catches drift.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "@usage-spec/commander";
import { buildProgram } from "../src/cli/index.js";

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), "..");
const TARGET = path.join(ROOT, "usage.kdl");
const HEADER = `// Generated by scripts/gen-usage.ts — do not edit by hand.
// Run \`pnpm run gen-usage\` to regenerate after touching the commander tree.

`;

export function buildSpec(): string {
  const program = buildProgram();
  return HEADER + generate(program, "gmail");
}

export interface UsageCheckResult {
  ok: boolean;
  message: string;
}

export function checkUsageFile(target: string, fresh = buildSpec()): UsageCheckResult {
  if (!fs.existsSync(target)) {
    return {
      ok: false,
      message: "usage.kdl is missing. Run `pnpm run gen-usage` and commit the result.\n",
    };
  }
  const committed = fs.readFileSync(target, "utf8");
  if (committed !== fresh) {
    return {
      ok: false,
      message: "usage.kdl is out of date. Run `pnpm run gen-usage` and commit the result.\n",
    };
  }
  return {
    ok: true,
    message: "usage.kdl is in sync with the commander tree.\n",
  };
}

export function run(argv = process.argv, target = TARGET): number {
  const isCheck = argv.includes("--check");
  const fresh = buildSpec();

  if (isCheck) {
    const result = checkUsageFile(target, fresh);
    process.stderr.write(result.message);
    return result.ok ? 0 : 1;
  }

  fs.writeFileSync(target, fresh);
  process.stderr.write(`Wrote ${target} (${fresh.length} bytes)\n`);
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  process.exitCode = run();
}
