#!/usr/bin/env node
/**
 * Generate `usage.kdl` from the commander tree.
 *
 * The [`usage`](https://usage.jdx.dev) Rust binary consumes the KDL spec to
 * produce shell completions (bash/zsh/fish/PowerShell/nu) and manpages.
 *
 * Run:
 *   pnpm run gen-usage           — regenerate and write usage.kdl
 *   pnpm run gen-usage --check   — fail if the committed file is out of date
 *
 * `pnpm verify` chains the `--check` mode so CI catches drift.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generate } from "@usage-spec/commander";
import { buildProgram } from "../src/cli/index.js";

const __filename = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(__filename), "..");
const TARGET = path.join(ROOT, "usage.kdl");
const HEADER = `// Generated by scripts/gen-usage.ts — do not edit by hand.
// Run \`pnpm run gen-usage\` to regenerate after touching the commander tree.

`;

function buildSpec(): string {
  const program = buildProgram();
  return HEADER + generate(program, "gmail");
}

function main(): void {
  const isCheck = process.argv.includes("--check");
  const fresh = buildSpec();

  if (isCheck) {
    if (!fs.existsSync(TARGET)) {
      process.stderr.write(
        "usage.kdl is missing. Run `pnpm run gen-usage` and commit the result.\n",
      );
      process.exit(1);
    }
    const committed = fs.readFileSync(TARGET, "utf8");
    if (committed !== fresh) {
      process.stderr.write(
        "usage.kdl is out of date. Run `pnpm run gen-usage` and commit the result.\n",
      );
      process.exit(1);
    }
    process.stderr.write("usage.kdl is in sync with the commander tree.\n");
    return;
  }

  fs.writeFileSync(TARGET, fresh);
  process.stderr.write(`Wrote ${TARGET} (${fresh.length} bytes)\n`);
}

main();
